var hierarchy =
[
    [ "fst::AE< T, Collection >", "structfst_1_1AE.html", null ],
    [ "fst::AE< T, std::map< unsigned int, T > >", "structfst_1_1AE_3_01T_00_01std_1_1map_3_01unsigned_01int_00_01T_01_4_01_4.html", null ],
    [ "fst::AE< T, std::vector< T > >", "structfst_1_1AE_3_01T_00_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "fst::AE< T, TropicalSparseTupleWeight< T > >", "structfst_1_1AE_3_01T_00_01TropicalSparseTupleWeight_3_01T_01_4_01_4.html", null ],
    [ "ucam::hifst::AlilatsToSparseWeightLatsData< KenLMModelT >", "classucam_1_1hifst_1_1AlilatsToSparseWeightLatsData.html", null ],
    [ "fst::ApplyLanguageModelOnTheFly< Arc, MakeWeightT, KenLMModelT, IdBridgeT >", "classfst_1_1ApplyLanguageModelOnTheFly.html", null ],
    [ "ucam::fsttools::ApplyLMData< KenLMModelT >", "structucam_1_1fsttools_1_1ApplyLMData.html", null ],
    [ "ucam::lmbr::ApplyPosteriors", "classucam_1_1lmbr_1_1ApplyPosteriors.html", null ],
    [ "Bleu", "classBleu.html", null ],
    [ "BleuStats", "classBleuStats.html", null ],
    [ "fst::CompareHyp", "classfst_1_1CompareHyp.html", null ],
    [ "ucam::hifst::CompareTool", "classucam_1_1hifst_1_1CompareTool.html", [
      [ "ucam::hifst::PatternCompareTool", "classucam_1_1hifst_1_1PatternCompareTool.html", null ]
    ] ],
    [ "CompositeList", "classCompositeList.html", null ],
    [ "ucam::lmbr::ComputePosteriors", "classucam_1_1lmbr_1_1ComputePosteriors.html", null ],
    [ "ucam::hifst::conditions", "structucam_1_1hifst_1_1conditions.html", null ],
    [ "ucam::hifst::CYKbackpointers", "classucam_1_1hifst_1_1CYKbackpointers.html", null ],
    [ "ucam::hifst::CYKdata", "structucam_1_1hifst_1_1CYKdata.html", null ],
    [ "ucam::hifst::CYKgrid", "classucam_1_1hifst_1_1CYKgrid.html", null ],
    [ "DataForCyK", "structDataForCyK.html", null ],
    [ "DataForPatternsToInstancesTask", "classDataForPatternsToInstancesTask.html", null ],
    [ "googletesting::DataForReferenceFilter", "classgoogletesting_1_1DataForReferenceFilter.html", null ],
    [ "DataForSentenceSpecificGrammarTask", "structDataForSentenceSpecificGrammarTask.html", null ],
    [ "googletesting::DataForStats", "structgoogletesting_1_1DataForStats.html", null ],
    [ "googletesting::DataTest1", "classgoogletesting_1_1DataTest1.html", null ],
    [ "googletesting::DataTest2", "classgoogletesting_1_1DataTest2.html", null ],
    [ "DebugMertAlgorithm", "classDebugMertAlgorithm.html", null ],
    [ "Directions", "classDirections.html", null ],
    [ "ucam::fsttools::DisambigData< KenLMModelT >", "structucam_1_1fsttools_1_1DisambigData.html", null ],
    [ "fst::DotProductMap< T >", "structfst_1_1DotProductMap.html", null ],
    [ "EnumerateVocab", null, [
      [ "lm::HifstEnumerateVocab", "classlm_1_1HifstEnumerateVocab.html", null ]
    ] ],
    [ "ErrorSurface< RD >", "classErrorSurface.html", null ],
    [ "fst::Expand", "structfst_1_1Expand.html", null ],
    [ "ucam::hifst::ExpandedNumStatesRTN< Arc >", "classucam_1_1hifst_1_1ExpandedNumStatesRTN.html", null ],
    [ "ucam::util::FastForwardRead< StreamT >", "classucam_1_1util_1_1FastForwardRead.html", null ],
    [ "ucam::util::FastForwardRead< ucam::util::iszfstream >", "classucam_1_1util_1_1FastForwardRead.html", null ],
    [ "FunctionArc", "structFunctionArc.html", null ],
    [ "FunctionToStdMapper", "classFunctionToStdMapper.html", null ],
    [ "FunctionWeight", "classFunctionWeight.html", null ],
    [ "googletesting::functor_test", "structgoogletesting_1_1functor__test.html", null ],
    [ "googletesting::functor_test2", "structgoogletesting_1_1functor__test2.html", null ],
    [ "fst::GeneralMapper< FromArc, ToArc, M >", "structfst_1_1GeneralMapper.html", null ],
    [ "fst::GenericWeightAutoMapper< Arc, WeightMakerFunctorT >", "classfst_1_1GenericWeightAutoMapper.html", null ],
    [ "fst::GenericWeightMapper< FromArc, ToArc, WeightMakerFunctorT >", "classfst_1_1GenericWeightMapper.html", null ],
    [ "fst::GetNGrams< Arc >", "classfst_1_1GetNGrams.html", null ],
    [ "fst::GetWeight< Arc >", "structfst_1_1GetWeight.html", null ],
    [ "fst::GetWeight< LexStdArc >", "structfst_1_1GetWeight_3_01LexStdArc_01_4.html", null ],
    [ "ucam::hifst::GrammarData", "structucam_1_1hifst_1_1GrammarData.html", null ],
    [ "hasheqvecint64", "classhasheqvecint64.html", null ],
    [ "ucam::util::hasheqvecuint", "classucam_1_1util_1_1hasheqvecuint.html", null ],
    [ "ucam::hifst::HifstClientTaskData", "classucam_1_1hifst_1_1HifstClientTaskData.html", null ],
    [ "ucam::hifst::HifstTaskData< KenLMModelT >", "classucam_1_1hifst_1_1HifstTaskData.html", null ],
    [ "ucam::hifst::HifstTaskData<>", "classucam_1_1hifst_1_1HifstTaskData.html", null ],
    [ "fst::Hyp< Arc >", "structfst_1_1Hyp.html", [
      [ "HypW< Arc >", "structHypW.html", null ]
    ] ],
    [ "fst::hypcost", "structfst_1_1hypcost.html", null ],
    [ "ucam::fsttools::IdBridge", "classucam_1_1fsttools_1_1IdBridge.html", null ],
    [ "IntegerEncRefs", "classIntegerEncRefs.html", null ],
    [ "IntervalData< ErrorStats >", "classIntervalData.html", null ],
    [ "ucam::util::iszfstream", "classucam_1_1util_1_1iszfstream.html", null ],
    [ "iterator", null, [
      [ "CompositeList::cl_iterator", "classCompositeList_1_1cl__iterator.html", null ]
    ] ],
    [ "ucam::fsttools::KenLMData< KenLMModelT >", "structucam_1_1fsttools_1_1KenLMData.html", null ],
    [ "fst::LexStdToStdMapper", "structfst_1_1LexStdToStdMapper.html", null ],
    [ "fst::LexToStd", "structfst_1_1LexToStd.html", null ],
    [ "ucam::lmbr::LmbrTaskData", "classucam_1_1lmbr_1_1LmbrTaskData.html", null ],
    [ "ucam::lmbr::lmbrtunedata", "structucam_1_1lmbr_1_1lmbrtunedata.html", null ],
    [ "LMertAlgorithm", "classLMertAlgorithm.html", null ],
    [ "ucam::hifst::LocalPruningConditions", "classucam_1_1hifst_1_1LocalPruningConditions.html", null ],
    [ "fst::MakeSparseVectorWeight< Arc >", "structfst_1_1MakeSparseVectorWeight.html", null ],
    [ "fst::MakeSparseVectorWeight< LexStdArc >", "structfst_1_1MakeSparseVectorWeight_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< Arc >", "structfst_1_1MakeWeight.html", null ],
    [ "fst::MakeWeight2< Arc >", "structfst_1_1MakeWeight2.html", null ],
    [ "fst::MakeWeight2< LexStdArc >", "structfst_1_1MakeWeight2_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< LexStdArc >", "structfst_1_1MakeWeight_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< TupleArc32 >", "structfst_1_1MakeWeight_3_01TupleArc32_01_4.html", null ],
    [ "ucam::hifst::ManualReplaceFstByArc< Arc >", "classucam_1_1hifst_1_1ManualReplaceFstByArc.html", null ],
    [ "MERT", "structMERT.html", null ],
    [ "MertEnvelope", "classMertEnvelope.html", null ],
    [ "MertLattice", "classMertLattice.html", null ],
    [ "MertLine", "classMertLine.html", null ],
    [ "MertOpt", "structMertOpt.html", null ],
    [ "fst::MultiUnionRational< Arc >", "classfst_1_1MultiUnionRational.html", null ],
    [ "fst::MultiUnionReplace< Arc >", "classfst_1_1MultiUnionReplace.html", null ],
    [ "ucam::hifst::NonTerminalHierarchy", "classucam_1_1hifst_1_1NonTerminalHierarchy.html", null ],
    [ "ucam::util::NumberRangeInterface< NumberType >", "classucam_1_1util_1_1NumberRangeInterface.html", [
      [ "ucam::util::InfiniteRange< NumberType >", "classucam_1_1util_1_1InfiniteRange.html", null ],
      [ "ucam::util::NumberRange< NumberType >", "classucam_1_1util_1_1NumberRange.html", null ],
      [ "ucam::util::OneRange< NumberType >", "classucam_1_1util_1_1OneRange.html", null ]
    ] ],
    [ "ucam::util::NumberRangeInterface< float >", "classucam_1_1util_1_1NumberRangeInterface.html", [
      [ "ucam::util::NumberRange< float >", "classucam_1_1util_1_1NumberRange.html", null ]
    ] ],
    [ "ucam::hifst::OptimizeMachine< Arc >", "classucam_1_1hifst_1_1OptimizeMachine.html", null ],
    [ "ucam::hifst::OptimizeMachineNoDetMin< Arc >", "classucam_1_1hifst_1_1OptimizeMachineNoDetMin.html", null ],
    [ "Optimizer", "classOptimizer.html", [
      [ "OptimizerImpl< Algo, ErrorSurface >", "classOptimizerImpl.html", [
        [ "PowellOptimizer< Algo, ErrorSurface >", "classPowellOptimizer.html", null ],
        [ "RandomOptimizer< Algo, ErrorSurface >", "classRandomOptimizer.html", null ]
      ] ]
    ] ],
    [ "OptimizeTask< Algo, ErrorSurface >", "classOptimizeTask.html", null ],
    [ "ucam::util::oszfstream", "classucam_1_1util_1_1oszfstream.html", null ],
    [ "ParamsConfig", "classParamsConfig.html", null ],
    [ "fst::ParamsInit< T >", "structfst_1_1ParamsInit.html", null ],
    [ "ucam::util::ParamsInit< T >", "structucam_1_1util_1_1ParamsInit.html", null ],
    [ "ucam::util::PatternAddress< T >", "classucam_1_1util_1_1PatternAddress.html", null ],
    [ "ucam::hifst::posindex", "structucam_1_1hifst_1_1posindex.html", null ],
    [ "ucam::hifst::PosIndexCompare", "classucam_1_1hifst_1_1PosIndexCompare.html", null ],
    [ "googletesting::PostProTaskData", "structgoogletesting_1_1PostProTaskData.html", null ],
    [ "ucam::util::PQwmapcompare", "classucam_1_1util_1_1PQwmapcompare.html", null ],
    [ "googletesting::PreProTaskData", "structgoogletesting_1_1PreProTaskData.html", null ],
    [ "PruneStats", "structPruneStats.html", null ],
    [ "RandDirGenerator", "classRandDirGenerator.html", null ],
    [ "RefsData", "classRefsData.html", null ],
    [ "ucam::util::RegistryPO", "classucam_1_1util_1_1RegistryPO.html", null ],
    [ "fst::RelabelUtil< Arc >", "classfst_1_1RelabelUtil.html", null ],
    [ "fst::RelabelUtil< TupleArc32 >", "classfst_1_1RelabelUtil.html", null ],
    [ "googletesting::RemoveWeight", "structgoogletesting_1_1RemoveWeight.html", null ],
    [ "ucam::hifst::ReplaceFstByArc< Arc >", "classucam_1_1hifst_1_1ReplaceFstByArc.html", null ],
    [ "ucam::hifst::RTN< Arc >", "classucam_1_1hifst_1_1RTN.html", null ],
    [ "ucam::util::Runner< SingleThreadedFunctorT, MultiThreadedFunctorT >", "classucam_1_1util_1_1Runner.html", null ],
    [ "ucam::util::Runner2< SingleThreadedFunctorT, MultiThreadedFunctorT >", "classucam_1_1util_1_1Runner2.html", null ],
    [ "ucam::util::Runner3< SingleThreadedFunctorT, MultiThreadedFunctorT, ServerFunctorT >", "classucam_1_1util_1_1Runner3.html", null ],
    [ "fst::ScaleWeight< Arc >", "structfst_1_1ScaleWeight.html", null ],
    [ "fst::ScaleWeight< LexStdArc >", "structfst_1_1ScaleWeight_3_01LexStdArc_01_4.html", null ],
    [ "Scorer", "classScorer.html", [
      [ "ScorerImpl< RefData >", "classScorerImpl.html", null ]
    ] ],
    [ "ucam::hifst::SentenceSpecificGrammarData", "structucam_1_1hifst_1_1SentenceSpecificGrammarData.html", null ],
    [ "mertfst::ShortestDistanceOptions< Arc, Queue, ArcFilter >", "structmertfst_1_1ShortestDistanceOptions.html", null ],
    [ "mertfst::ShortestDistanceState< Arc, Queue, ArcFilter >", "classmertfst_1_1ShortestDistanceState.html", null ],
    [ "ucam::util::silent", "classucam_1_1util_1_1silent.html", null ],
    [ "SparsePowerWeight", null, [
      [ "fst::TropicalSparseTupleWeight< T >", "classfst_1_1TropicalSparseTupleWeight.html", null ],
      [ "fst::TropicalSparseTupleWeight< T >", "classfst_1_1TropicalSparseTupleWeight.html", null ]
    ] ],
    [ "ucam::fsttools::StatsData", "structucam_1_1fsttools_1_1StatsData.html", null ],
    [ "fst::StdToLexStdMapper", "structfst_1_1StdToLexStdMapper.html", null ],
    [ "fst::StdToTropicalSparseMapper< W >", "structfst_1_1StdToTropicalSparseMapper.html", null ],
    [ "fst::StdToVector< T >", "structfst_1_1StdToVector.html", null ],
    [ "TaskData", "structTaskData.html", null ],
    [ "ucam::util::TaskFunctor< Data >", "classucam_1_1util_1_1TaskFunctor.html", null ],
    [ "ucam::util::TaskInterface< Data >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "googletesting::PostEditTask< Data >", "classgoogletesting_1_1PostEditTask.html", null ],
      [ "googletesting::Task1< Data >", "classgoogletesting_1_1Task1.html", null ],
      [ "googletesting::Task2< Data >", "classgoogletesting_1_1Task2.html", null ],
      [ "googletesting::Task2b< Data >", "classgoogletesting_1_1Task2b.html", null ],
      [ "googletesting::Task3< Data >", "classgoogletesting_1_1Task3.html", null ],
      [ "googletesting::Task4< Data >", "classgoogletesting_1_1Task4.html", null ],
      [ "ucam::fsttools::ApplyLanguageModelTask< Data, KenLMModelT, Arc >", "classucam_1_1fsttools_1_1ApplyLanguageModelTask.html", null ],
      [ "ucam::fsttools::DisambigTask< Data, KenLMModelT, Arc >", "classucam_1_1fsttools_1_1DisambigTask.html", null ],
      [ "ucam::fsttools::LoadLanguageModelTask< Data, KenLMModelT >", "classucam_1_1fsttools_1_1LoadLanguageModelTask.html", null ],
      [ "ucam::fsttools::LoadUnimapTask< Data, Arc >", "classucam_1_1fsttools_1_1LoadUnimapTask.html", null ],
      [ "ucam::fsttools::LoadWordMapTask< Data >", "classucam_1_1fsttools_1_1LoadWordMapTask.html", null ],
      [ "ucam::fsttools::MultiThreadedApplyLanguageModelTask< Data, KenLMModelT, Arc >", "classucam_1_1fsttools_1_1MultiThreadedApplyLanguageModelTask.html", null ],
      [ "ucam::fsttools::ReadFstTask< Data, Arc >", "classucam_1_1fsttools_1_1ReadFstTask.html", null ],
      [ "ucam::fsttools::SingleThreadedApplyLanguageModelTask< Data, KenLMModelT, Arc >", "classucam_1_1fsttools_1_1SingleThreadedApplyLanguageModelTask.html", null ],
      [ "ucam::fsttools::SpeedStatsTask< Data >", "classucam_1_1fsttools_1_1SpeedStatsTask.html", null ],
      [ "ucam::fsttools::WriteFstTask< Data, Arc >", "classucam_1_1fsttools_1_1WriteFstTask.html", null ],
      [ "ucam::hifst::CYKParserTask< Data >", "classucam_1_1hifst_1_1CYKParserTask.html", null ],
      [ "ucam::hifst::DumpNbestFeaturesTask< Data, Arc >", "classucam_1_1hifst_1_1DumpNbestFeaturesTask.html", null ],
      [ "ucam::hifst::GrammarTask< Data >", "classucam_1_1hifst_1_1GrammarTask.html", null ],
      [ "ucam::hifst::HifstServerTask< Data, KenLMModelT >", "classucam_1_1hifst_1_1HifstServerTask.html", null ],
      [ "ucam::hifst::HifstStatsTask< Data >", "classucam_1_1hifst_1_1HifstStatsTask.html", null ],
      [ "ucam::hifst::HiFSTTask< Data, KenLMModelT, Arc, OptimizeT, CYKdataT, MultiUnionT, ExpandedNumStatesRTNT, ReplaceFstByArcT, RTNT >", "classucam_1_1hifst_1_1HiFSTTask.html", null ],
      [ "ucam::hifst::LoadSparseWeightFlowerLatticeTask< Data >", "classucam_1_1hifst_1_1LoadSparseWeightFlowerLatticeTask.html", null ],
      [ "ucam::hifst::MultiThreadedAliLatsToSparseVecLatsTask< Data, KenLMModelT >", "classucam_1_1hifst_1_1MultiThreadedAliLatsToSparseVecLatsTask.html", null ],
      [ "ucam::hifst::MultiThreadedCreateSentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1MultiThreadedCreateSentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::MultiThreadedHifstTask< Data, KenLMModelT >", "classucam_1_1hifst_1_1MultiThreadedHifstTask.html", null ],
      [ "ucam::hifst::PatternsToInstancesTask< Data >", "classucam_1_1hifst_1_1PatternsToInstancesTask.html", null ],
      [ "ucam::hifst::PostProTask< Data, Arc >", "classucam_1_1hifst_1_1PostProTask.html", null ],
      [ "ucam::hifst::PreProTask< Data >", "classucam_1_1hifst_1_1PreProTask.html", null ],
      [ "ucam::hifst::ReferenceFilterTask< Data, Arc >", "classucam_1_1hifst_1_1ReferenceFilterTask.html", null ],
      [ "ucam::hifst::SentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1SentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::SingleThreadedAliLatsToSparseVecLatsTask< Data, KenLMModelT >", "classucam_1_1hifst_1_1SingleThreadedAliLatsToSparseVecLatsTask.html", null ],
      [ "ucam::hifst::SingleThreadedCreateSentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1SingleThreadedCreateSentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::SingleThreadedHifstClientTask< Data >", "classucam_1_1hifst_1_1SingleThreadedHifstClientTask.html", null ],
      [ "ucam::hifst::SingleThreadedHifstTask< Data, KenLMModelT >", "classucam_1_1hifst_1_1SingleThreadedHifstTask.html", null ],
      [ "ucam::hifst::SparseWeightVectorLatticesTask< Data, Arc >", "classucam_1_1hifst_1_1SparseWeightVectorLatticesTask.html", null ],
      [ "ucam::lmbr::LmbrTask< Data >", "classucam_1_1lmbr_1_1LmbrTask.html", null ],
      [ "ucam::lmbr::MultiThreadedLmbrTask< Data >", "classucam_1_1lmbr_1_1MultiThreadedLmbrTask.html", null ],
      [ "ucam::lmbr::SingleThreadedLmbrTask< Data >", "classucam_1_1lmbr_1_1SingleThreadedLmbrTask.html", null ]
    ] ],
    [ "ucam::util::TaskInterface< uh::HifstTaskData<> >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::hifst::CYKParserTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1CYKParserTask.html", null ],
      [ "ucam::hifst::GrammarTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1GrammarTask.html", null ],
      [ "ucam::hifst::SentenceSpecificGrammarTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1SentenceSpecificGrammarTask.html", null ]
    ] ],
    [ "Test", null, [
      [ "HifstTest", "classHifstTest.html", null ]
    ] ],
    [ "TGMertAlgorithm< Arc, T >", "classTGMertAlgorithm.html", null ],
    [ "ucam::lmbr::Theta", "classucam_1_1lmbr_1_1Theta.html", null ],
    [ "ucam::util::TrivialThreadPool", "classucam_1_1util_1_1TrivialThreadPool.html", null ],
    [ "TuneSet", "classTuneSet.html", null ],
    [ "TuneWpMain< Arc >", "classTuneWpMain.html", null ],
    [ "unary_function", null, [
      [ "hashfvecint64", "classhashfvecint64.html", null ],
      [ "ucam::util::hashfvecuint", "classucam_1_1util_1_1hashfvecuint.html", null ]
    ] ],
    [ "VectorToFunctionMapper< FromArc, T >", "classVectorToFunctionMapper.html", null ],
    [ "fst::VectorToStd< T >", "structfst_1_1VectorToStd.html", null ],
    [ "ucam::util::WordMapper", "classucam_1_1util_1_1WordMapper.html", null ],
    [ "fst::WordPenaltyMapper< Arc >", "classfst_1_1WordPenaltyMapper.html", null ]
];