var hierarchy =
[
    [ "fst::AE< T, Collection >", "structfst_1_1AE.html", null ],
    [ "fst::AE< T, std::map< unsigned int, T > >", "structfst_1_1AE_3_01T_00_01std_1_1map_3_01unsigned_01int_00_01T_01_4_01_4.html", null ],
    [ "fst::AE< T, std::vector< T > >", "structfst_1_1AE_3_01T_00_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "fst::AE< T, TropicalSparseTupleWeight< T > >", "structfst_1_1AE_3_01T_00_01TropicalSparseTupleWeight_3_01T_01_4_01_4.html", null ],
    [ "ucam::hifst::AlilatsToSparseWeightLatsData< ArcT >", "classucam_1_1hifst_1_1AlilatsToSparseWeightLatsData.html", null ],
    [ "fst::ApplyLanguageModelOnTheFlyInterface< ArcT >", "structfst_1_1ApplyLanguageModelOnTheFlyInterface.html", null ],
    [ "fst::ApplyLanguageModelOnTheFlyInterface< Arc >", "structfst_1_1ApplyLanguageModelOnTheFlyInterface.html", [
      [ "fst::ApplyLanguageModelOnTheFly< Arc, MakeWeightT, KenLMModelT, IdBridgeT, HackScoreT >", "classfst_1_1ApplyLanguageModelOnTheFly.html", null ]
    ] ],
    [ "ucam::fsttools::ApplyLMData< ArcT >", "structucam_1_1fsttools_1_1ApplyLMData.html", null ],
    [ "ucam::lmbr::ApplyPosteriors", "classucam_1_1lmbr_1_1ApplyPosteriors.html", null ],
    [ "ucam::fsttools::Bleu", "classucam_1_1fsttools_1_1Bleu.html", null ],
    [ "Bleu", "classBleu.html", null ],
    [ "ucam::fsttools::BleuScorer", "classucam_1_1fsttools_1_1BleuScorer.html", null ],
    [ "ucam::fsttools::BleuStats", "classucam_1_1fsttools_1_1BleuStats.html", null ],
    [ "BleuStats", "classBleuStats.html", null ],
    [ "uk.ac.cam.eng.util.CLI", "classuk_1_1ac_1_1cam_1_1eng_1_1util_1_1CLI.html", null ],
    [ "fst::CompareHyp", "classfst_1_1CompareHyp.html", null ],
    [ "ucam::hifst::CompareTool", "classucam_1_1hifst_1_1CompareTool.html", [
      [ "ucam::hifst::PatternCompareTool", "classucam_1_1hifst_1_1PatternCompareTool.html", null ]
    ] ],
    [ "CompositeList", "classCompositeList.html", null ],
    [ "ucam::lmbr::ComputePosteriors", "classucam_1_1lmbr_1_1ComputePosteriors.html", null ],
    [ "ucam::hifst::conditions", "structucam_1_1hifst_1_1conditions.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.util.CopyRecordsForTesting", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1CopyRecordsForTesting.html", null ],
    [ "ucam::hifst::CYKbackpointers", "classucam_1_1hifst_1_1CYKbackpointers.html", null ],
    [ "ucam::hifst::CYKdata", "structucam_1_1hifst_1_1CYKdata.html", null ],
    [ "ucam::hifst::CYKgrid", "classucam_1_1hifst_1_1CYKgrid.html", null ],
    [ "DataForCyK", "structDataForCyK.html", null ],
    [ "DataForPatternsToInstancesTask", "classDataForPatternsToInstancesTask.html", null ],
    [ "googletesting::DataForReferenceFilter", "classgoogletesting_1_1DataForReferenceFilter.html", null ],
    [ "DataForSentenceSpecificGrammarTask", "structDataForSentenceSpecificGrammarTask.html", null ],
    [ "googletesting::DataForStats", "structgoogletesting_1_1DataForStats.html", null ],
    [ "googletesting::DataTest1", "classgoogletesting_1_1DataTest1.html", null ],
    [ "googletesting::DataTest2", "classgoogletesting_1_1DataTest2.html", null ],
    [ "DebugMertAlgorithm", "classDebugMertAlgorithm.html", null ],
    [ "Directions", "classDirections.html", null ],
    [ "ucam::fsttools::DisambigData", "structucam_1_1fsttools_1_1DisambigData.html", null ],
    [ "DisambigFunctor< ArcT >", "structDisambigFunctor.html", null ],
    [ "fst::DotProductMap< T >", "structfst_1_1DotProductMap.html", null ],
    [ "EnumerateVocab", null, [
      [ "lm::HifstEnumerateVocab< WordMapperT >", "classlm_1_1HifstEnumerateVocab.html", null ]
    ] ],
    [ "uk.ac.cam.eng.rule.retrieval.EnumRuleType", "enumuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1retrieval_1_1EnumRuleType.html", null ],
    [ "ErrorSurface< RD >", "classErrorSurface.html", null ],
    [ "fst::Expand", "structfst_1_1Expand.html", null ],
    [ "ucam::hifst::ExpandedNumStatesRTN< Arc >", "classucam_1_1hifst_1_1ExpandedNumStatesRTN.html", null ],
    [ "ucam::fsttools::ExpandPathsWithTopologicalWeights< MapCursorT, FeatureTrackerT >", "classucam_1_1fsttools_1_1ExpandPathsWithTopologicalWeights.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.util.ExtractorDataLoader", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1ExtractorDataLoader.html", null ],
    [ "ucam::util::FastForwardRead< StreamT >", "classucam_1_1util_1_1FastForwardRead.html", null ],
    [ "ucam::util::FastForwardRead< ucam::util::iszfstream >", "classucam_1_1util_1_1FastForwardRead.html", null ],
    [ "uk.ac.cam.eng.rule.features.Feature", "enumuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1features_1_1Feature.html", null ],
    [ "uk.ac.cam.eng.rule.features.FeatureFunctionRegistry", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1features_1_1FeatureFunctionRegistry.html", null ],
    [ "uk.ac.cam.eng.rule.features.FeatureFunctions", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1features_1_1FeatureFunctions.html", null ],
    [ "uk.ac.cam.eng.rule.features.FeatureRegistry", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1features_1_1FeatureRegistry.html", null ],
    [ "ucam::fsttools::FeatureTracker", "classucam_1_1fsttools_1_1FeatureTracker.html", null ],
    [ "ucam::fsttools::FeatureTrackerRev", "classucam_1_1fsttools_1_1FeatureTrackerRev.html", null ],
    [ "FunctionArc", "structFunctionArc.html", null ],
    [ "FunctionToStdMapper", "classFunctionToStdMapper.html", null ],
    [ "FunctionWeight", "classFunctionWeight.html", null ],
    [ "googletesting::functor_test", "structgoogletesting_1_1functor__test.html", null ],
    [ "googletesting::functor_test2", "structgoogletesting_1_1functor__test2.html", null ],
    [ "fst::GeneralMapper< FromArc, ToArc, M >", "structfst_1_1GeneralMapper.html", null ],
    [ "ucam::hifst::GenerateTrivialFst< Arc >", "structucam_1_1hifst_1_1GenerateTrivialFst.html", null ],
    [ "fst::GenericArcAutoMapper< Arc, ArcMakerFunctorT >", "classfst_1_1GenericArcAutoMapper.html", null ],
    [ "fst::GenericArcMapper< FromArc, ToArc, ArcMakerFunctorT >", "classfst_1_1GenericArcMapper.html", null ],
    [ "fst::GenericWeightAutoMapper< Arc, WeightMakerFunctorT >", "classfst_1_1GenericWeightAutoMapper.html", null ],
    [ "fst::GenericWeightMapper< FromArc, ToArc, WeightMakerFunctorT >", "classfst_1_1GenericWeightMapper.html", null ],
    [ "fst::GetNGrams< Arc >", "classfst_1_1GetNGrams.html", null ],
    [ "fst::GetWeight< Arc >", "structfst_1_1GetWeight.html", null ],
    [ "fst::GetWeight< LexStdArc >", "structfst_1_1GetWeight_3_01LexStdArc_01_4.html", null ],
    [ "ucam::hifst::GrammarData", "structucam_1_1hifst_1_1GrammarData.html", null ],
    [ "fst::HackScore< StateT >", "structfst_1_1HackScore.html", null ],
    [ "fst::HackScore< lm::np::State >", "structfst_1_1HackScore_3_01lm_1_1np_1_1State_01_4.html", null ],
    [ "fst::HackScoreBilingual< StateT >", "structfst_1_1HackScoreBilingual.html", null ],
    [ "fst::HackScoreBilingual< lm::np::State >", "structfst_1_1HackScoreBilingual_3_01lm_1_1np_1_1State_01_4.html", null ],
    [ "ucam::util::HashEqVec< VecT >", "classucam_1_1util_1_1HashEqVec.html", null ],
    [ "hasheqvecint64", "classhasheqvecint64.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.util.HFilePrint", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1HFilePrint.html", null ],
    [ "ucam::hifst::HifstClientTaskData", "classucam_1_1hifst_1_1HifstClientTaskData.html", null ],
    [ "ucam::hifst::HifstTaskData< ArcT >", "classucam_1_1hifst_1_1HifstTaskData.html", null ],
    [ "ucam::hifst::HifstTaskData<>", "classucam_1_1hifst_1_1HifstTaskData.html", null ],
    [ "fst::Hyp< Arc >", "structfst_1_1Hyp.html", [
      [ "HypW< Arc >", "structHypW.html", null ],
      [ "HypW< Arc >", "structHypW.html", null ]
    ] ],
    [ "fst::hypcost", "structfst_1_1hypcost.html", null ],
    [ "ucam::fsttools::IdBridge", "classucam_1_1fsttools_1_1IdBridge.html", null ],
    [ "IntegerEncRefs", "classIntegerEncRefs.html", null ],
    [ "ucam::lmert::IntervalBoundary", "classucam_1_1lmert_1_1IntervalBoundary.html", null ],
    [ "IntervalData< ErrorStats >", "classIntervalData.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.datatypes.IntWritableCache", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1IntWritableCache.html", null ],
    [ "ucam::util::iszfstream", "classucam_1_1util_1_1iszfstream.html", null ],
    [ "Iterable", null, [
      [ "uk.ac.cam.eng.rule.retrieval.HFileRuleReader", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1retrieval_1_1HFileRuleReader.html", null ]
    ] ],
    [ "iterator", null, [
      [ "CompositeList::cl_iterator", "classCompositeList_1_1cl__iterator.html", null ]
    ] ],
    [ "ucam::fsttools::KenLMData", "structucam_1_1fsttools_1_1KenLMData.html", null ],
    [ "ucam::fsttools::KenLMModelHelper< KenLMModelT >", "structucam_1_1fsttools_1_1KenLMModelHelper.html", null ],
    [ "LabeledFeature< Value, Weight >", "structLabeledFeature.html", null ],
    [ "fst::LexStdToStdMapper", "structfst_1_1LexStdToStdMapper.html", null ],
    [ "fst::LexToStd", "structfst_1_1LexToStd.html", null ],
    [ "ucam::lmert::LineOptimize< Arc >", "classucam_1_1lmert_1_1LineOptimize.html", null ],
    [ "ucam::lmbr::LmbrTaskData", "classucam_1_1lmbr_1_1LmbrTaskData.html", null ],
    [ "ucam::lmbr::lmbrtunedata", "structucam_1_1lmbr_1_1lmbrtunedata.html", null ],
    [ "LMertAlgorithm", "classLMertAlgorithm.html", null ],
    [ "ucam::hifst::LocalPruningConditions", "classucam_1_1hifst_1_1LocalPruningConditions.html", null ],
    [ "ucam::fsttools::LRUCache", "classucam_1_1fsttools_1_1LRUCache.html", null ],
    [ "ucam::util::MainClass", "structucam_1_1util_1_1MainClass.html", null ],
    [ "fst::MakeSparseVectorWeight< Arc >", "structfst_1_1MakeSparseVectorWeight.html", null ],
    [ "fst::MakeSparseVectorWeight< LexStdArc >", "structfst_1_1MakeSparseVectorWeight_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< Arc >", "structfst_1_1MakeWeight.html", null ],
    [ "fst::MakeWeight2< Arc >", "structfst_1_1MakeWeight2.html", null ],
    [ "fst::MakeWeight2< LexStdArc >", "structfst_1_1MakeWeight2_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< LexStdArc >", "structfst_1_1MakeWeight_3_01LexStdArc_01_4.html", null ],
    [ "fst::MakeWeight< TupleArc32 >", "structfst_1_1MakeWeight_3_01TupleArc32_01_4.html", null ],
    [ "ucam::hifst::MakeWeightHifst< Arc >", "structucam_1_1hifst_1_1MakeWeightHifst.html", null ],
    [ "ucam::hifst::MakeWeightHifst< fst::LexStdArc >", "structucam_1_1hifst_1_1MakeWeightHifst_3_01fst_1_1LexStdArc_01_4.html", null ],
    [ "ucam::hifst::MakeWeightHifst< TupleArc32 >", "structucam_1_1hifst_1_1MakeWeightHifst_3_01TupleArc32_01_4.html", null ],
    [ "ucam::hifst::MakeWeightHifstLocalLm< Arc >", "structucam_1_1hifst_1_1MakeWeightHifstLocalLm.html", null ],
    [ "ucam::hifst::MakeWeightHifstLocalLm< fst::LexStdArc >", "structucam_1_1hifst_1_1MakeWeightHifstLocalLm_3_01fst_1_1LexStdArc_01_4.html", null ],
    [ "ucam::hifst::MakeWeightHifstLocalLm< TupleArc32 >", "structucam_1_1hifst_1_1MakeWeightHifstLocalLm_3_01TupleArc32_01_4.html", null ],
    [ "ucam::hifst::ManualReplaceFstByArc< Arc >", "classucam_1_1hifst_1_1ManualReplaceFstByArc.html", null ],
    [ "ucam::fsttools::MapCursor", "structucam_1_1fsttools_1_1MapCursor.html", null ],
    [ "ucam::fsttools::MapCursorRev", "structucam_1_1fsttools_1_1MapCursorRev.html", null ],
    [ "ucam::fsttools::MergeFeatures", "structucam_1_1fsttools_1_1MergeFeatures.html", null ],
    [ "MERT", "structMERT.html", null ],
    [ "MertEnvelope", "classMertEnvelope.html", null ],
    [ "ucam::lmert::MertEnvelope< Arc >", "classucam_1_1lmert_1_1MertEnvelope.html", null ],
    [ "MertLattice", "classMertLattice.html", null ],
    [ "ucam::lmert::MertLattice< Arc >", "classucam_1_1lmert_1_1MertLattice.html", null ],
    [ "ucam::lmert::MertLatticeWrap< Arc >", "classucam_1_1lmert_1_1MertLatticeWrap.html", null ],
    [ "MertLine", "classMertLine.html", null ],
    [ "ucam::lmert::MertLine< Arc >", "classucam_1_1lmert_1_1MertLine.html", null ],
    [ "MertOpt", "structMertOpt.html", null ],
    [ "fst::MultiUnionRational< Arc >", "classfst_1_1MultiUnionRational.html", null ],
    [ "fst::MultiUnionReplace< Arc >", "classfst_1_1MultiUnionReplace.html", null ],
    [ "ucam::hifst::NonTerminalHierarchy", "classucam_1_1hifst_1_1NonTerminalHierarchy.html", null ],
    [ "ucam::util::NoThreadPool", "structucam_1_1util_1_1NoThreadPool.html", null ],
    [ "ucam::fsttools::NullAction", "structucam_1_1fsttools_1_1NullAction.html", null ],
    [ "ucam::util::NumberRangeInterface< NumberType >", "classucam_1_1util_1_1NumberRangeInterface.html", [
      [ "ucam::util::InfiniteRange< NumberType >", "classucam_1_1util_1_1InfiniteRange.html", null ],
      [ "ucam::util::NumberRange< NumberType >", "classucam_1_1util_1_1NumberRange.html", null ],
      [ "ucam::util::OneRange< NumberType >", "classucam_1_1util_1_1OneRange.html", null ]
    ] ],
    [ "ucam::util::NumberRangeInterface< float >", "classucam_1_1util_1_1NumberRangeInterface.html", [
      [ "ucam::util::NumberRange< float >", "classucam_1_1util_1_1NumberRange.html", null ]
    ] ],
    [ "ucam::fsttools::OLabelToFeature", "structucam_1_1fsttools_1_1OLabelToFeature.html", null ],
    [ "ucam::hifst::OptimizeMachine< Arc >", "classucam_1_1hifst_1_1OptimizeMachine.html", null ],
    [ "ucam::hifst::OptimizeMachineNoDetMin< Arc >", "classucam_1_1hifst_1_1OptimizeMachineNoDetMin.html", null ],
    [ "Optimizer", "classOptimizer.html", [
      [ "OptimizerImpl< Algo, ErrorSurface >", "classOptimizerImpl.html", [
        [ "PowellOptimizer< Algo, ErrorSurface >", "classPowellOptimizer.html", null ],
        [ "RandomOptimizer< Algo, ErrorSurface >", "classRandomOptimizer.html", null ]
      ] ]
    ] ],
    [ "OptimizeTask< Algo, ErrorSurface >", "classOptimizeTask.html", null ],
    [ "ucam::util::oszfstream", "classucam_1_1util_1_1oszfstream.html", null ],
    [ "uk.ac.cam.eng.util.Pair< T, U >", "classuk_1_1ac_1_1cam_1_1eng_1_1util_1_1Pair.html", null ],
    [ "ParamsConfig", "classParamsConfig.html", null ],
    [ "ucam::util::ParamsInit< T >", "structucam_1_1util_1_1ParamsInit.html", null ],
    [ "fst::ParamsInit< T >", "structfst_1_1ParamsInit.html", null ],
    [ "ucam::util::PatternAddress< T >", "classucam_1_1util_1_1PatternAddress.html", null ],
    [ "ucam::hifst::posindex", "structucam_1_1hifst_1_1posindex.html", null ],
    [ "ucam::hifst::PosIndexCompare", "classucam_1_1hifst_1_1PosIndexCompare.html", null ],
    [ "googletesting::PostProTaskData", "structgoogletesting_1_1PostProTaskData.html", null ],
    [ "ucam::util::PQwmapcompare", "classucam_1_1util_1_1PQwmapcompare.html", null ],
    [ "googletesting::PreProTaskData", "structgoogletesting_1_1PreProTaskData.html", null ],
    [ "ucam::fsttools::ProjectDeterminizeAction", "structucam_1_1fsttools_1_1ProjectDeterminizeAction.html", null ],
    [ "ucam::fsttools::ProjectDeterminizeMinimizePushAction", "structucam_1_1fsttools_1_1ProjectDeterminizeMinimizePushAction.html", null ],
    [ "ucam::fsttools::ProjectDeterminizePushAction", "structucam_1_1fsttools_1_1ProjectDeterminizePushAction.html", null ],
    [ "PruneStats", "structPruneStats.html", null ],
    [ "RandDirGenerator", "classRandDirGenerator.html", null ],
    [ "ucam::lmert::RandomLineSearch< Arc >", "classucam_1_1lmert_1_1RandomLineSearch.html", null ],
    [ "RefsData", "classRefsData.html", null ],
    [ "ucam::util::RegistryPO", "classucam_1_1util_1_1RegistryPO.html", null ],
    [ "fst::RelabelUtil< Arc >", "classfst_1_1RelabelUtil.html", null ],
    [ "fst::RelabelUtil< TupleArc32 >", "classfst_1_1RelabelUtil.html", null ],
    [ "googletesting::RemoveWeight", "structgoogletesting_1_1RemoveWeight.html", null ],
    [ "ucam::hifst::ReplaceFstByArc< Arc >", "classucam_1_1hifst_1_1ReplaceFstByArc.html", null ],
    [ "ucam::hifst::RTN< Arc >", "classucam_1_1hifst_1_1RTN.html", null ],
    [ "uk.ac.cam.eng.extraction.RuleExtractorTest", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1RuleExtractorTest.html", null ],
    [ "uk.ac.cam.eng.rule.filtering.RuleFilter", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1filtering_1_1RuleFilter.html", null ],
    [ "ucam::hifst::RuleIdsToSparseWeightLatsData< KenLMModelT >", "classucam_1_1hifst_1_1RuleIdsToSparseWeightLatsData.html", null ],
    [ "uk.ac.cam.eng.rule.retrieval.RulePattern", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1retrieval_1_1RulePattern.html", null ],
    [ "uk.ac.cam.eng.rule.retrieval.RuleRetriever", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1retrieval_1_1RuleRetriever.html", null ],
    [ "ucam::hifst::RulesToWeightsMapperObject", "structucam_1_1hifst_1_1RulesToWeightsMapperObject.html", null ],
    [ "RunAlilatsToSplats< DataT, ArcT >", "structRunAlilatsToSplats.html", null ],
    [ "RunApplyLm< DataT, ArcT >", "structRunApplyLm.html", null ],
    [ "RunHifst< DataT, ArcT >", "structRunHifst.html", null ],
    [ "ucam::util::Runner< SingleThreadedFunctorT, MultiThreadedFunctorT >", "classucam_1_1util_1_1Runner.html", null ],
    [ "ucam::util::Runner2< SingleThreadedFunctorT, MultiThreadedFunctorT >", "classucam_1_1util_1_1Runner2.html", null ],
    [ "ucam::util::Runner3< SingleThreadedFunctorT, MultiThreadedFunctorT, ServerFunctorT >", "classucam_1_1util_1_1Runner3.html", null ],
    [ "ucam::fsttools::RunTask2< TaskOneT, TaskTwoT, DataT, ArcT >", "structucam_1_1fsttools_1_1RunTask2.html", null ],
    [ "ucam::fsttools::RunTask3< TaskOneT, TaskTwoT, TaskThreeT, DataT, ArcT >", "structucam_1_1fsttools_1_1RunTask3.html", null ],
    [ "Sample", "classSample.html", null ],
    [ "fst::Scale< StateT >", "structfst_1_1Scale.html", null ],
    [ "fst::Scale< lm::np::State >", "structfst_1_1Scale_3_01lm_1_1np_1_1State_01_4.html", null ],
    [ "fst::Scale< typename KenLMModelT::State >", "structfst_1_1Scale.html", null ],
    [ "fst::ScaleWeight< Arc >", "structfst_1_1ScaleWeight.html", null ],
    [ "fst::ScaleWeight< LexStdArc >", "structfst_1_1ScaleWeight_3_01LexStdArc_01_4.html", null ],
    [ "fst::Scorer< StateT, KenLMModelT, IdBridgeT, HackScoreT >", "structfst_1_1Scorer.html", null ],
    [ "Scorer", "classScorer.html", [
      [ "ScorerImpl< RefData >", "classScorerImpl.html", null ]
    ] ],
    [ "fst::Scorer< lm::np::State, lm::np::Model, IdBridgeT, HackScoreT >", "structfst_1_1Scorer_3_01lm_1_1np_1_1State_00_01lm_1_1np_1_1Model_00_01IdBridgeT_00_01HackScoreT_01_4.html", null ],
    [ "ucam::hifst::SentenceSpecificGrammarData", "structucam_1_1hifst_1_1SentenceSpecificGrammarData.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.util.SequenceFilePrint", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1SequenceFilePrint.html", null ],
    [ "mertfst::ShortestDistanceOptions< Arc, Queue, ArcFilter >", "structmertfst_1_1ShortestDistanceOptions.html", null ],
    [ "mertfst::ShortestDistanceState< Arc, Queue, ArcFilter >", "classmertfst_1_1ShortestDistanceState.html", null ],
    [ "uk.ac.cam.eng.rule.retrieval.SidePattern", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1retrieval_1_1SidePattern.html", null ],
    [ "ucam::util::silent", "classucam_1_1util_1_1silent.html", null ],
    [ "SparsePowerWeight", null, [
      [ "fst::TropicalSparseTupleWeight< T >", "classfst_1_1TropicalSparseTupleWeight.html", null ],
      [ "fst::TropicalSparseTupleWeight< T >", "classfst_1_1TropicalSparseTupleWeight.html", null ]
    ] ],
    [ "ucam::fsttools::SpeedStatsData", "structucam_1_1fsttools_1_1SpeedStatsData.html", null ],
    [ "fst::StateHandler< StateT >", "structfst_1_1StateHandler.html", null ],
    [ "ucam::fsttools::StateHandler", "structucam_1_1fsttools_1_1StateHandler.html", null ],
    [ "fst::StateHandler< lm::np::State >", "structfst_1_1StateHandler_3_01lm_1_1np_1_1State_01_4.html", null ],
    [ "fst::StateHandler< typename KenLMModelT::State >", "structfst_1_1StateHandler.html", null ],
    [ "ucam::fsttools::StatsData", "structucam_1_1fsttools_1_1StatsData.html", null ],
    [ "fst::StdToLexStdMapper", "structfst_1_1StdToLexStdMapper.html", null ],
    [ "fst::StdToTropicalSparseMapper< W >", "structfst_1_1StdToTropicalSparseMapper.html", null ],
    [ "fst::StdToVector< T >", "structfst_1_1StdToVector.html", null ],
    [ "TaskData", "structTaskData.html", null ],
    [ "ucam::util::TaskFunctor< Data >", "classucam_1_1util_1_1TaskFunctor.html", null ],
    [ "ucam::util::TaskInterface< Data >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "googletesting::PostEditTask< Data >", "classgoogletesting_1_1PostEditTask.html", null ],
      [ "googletesting::Task1< Data >", "classgoogletesting_1_1Task1.html", null ],
      [ "googletesting::Task2< Data >", "classgoogletesting_1_1Task2.html", null ],
      [ "googletesting::Task2b< Data >", "classgoogletesting_1_1Task2b.html", null ],
      [ "googletesting::Task3< Data >", "classgoogletesting_1_1Task3.html", null ],
      [ "googletesting::Task4< Data >", "classgoogletesting_1_1Task4.html", null ],
      [ "ucam::fsttools::ApplyBiLMTask< Data, Arc >", "classucam_1_1fsttools_1_1ApplyBiLMTask.html", null ],
      [ "ucam::fsttools::ApplyLanguageModelTask< Data, Arc >", "classucam_1_1fsttools_1_1ApplyLanguageModelTask.html", null ],
      [ "ucam::fsttools::DisambigTask< Data, Arc >", "classucam_1_1fsttools_1_1DisambigTask.html", null ],
      [ "ucam::fsttools::LoadLanguageModelTask< Data >", "classucam_1_1fsttools_1_1LoadLanguageModelTask.html", null ],
      [ "ucam::fsttools::LoadUnimapTask< Data, Arc >", "classucam_1_1fsttools_1_1LoadUnimapTask.html", null ],
      [ "ucam::fsttools::LoadWordMapTask< Data >", "classucam_1_1fsttools_1_1LoadWordMapTask.html", null ],
      [ "ucam::fsttools::OptimizeFstTask< Data, Arc >", "classucam_1_1fsttools_1_1OptimizeFstTask.html", null ],
      [ "ucam::fsttools::ReadFstTask< Data, Arc >", "classucam_1_1fsttools_1_1ReadFstTask.html", null ],
      [ "ucam::fsttools::SpeedStatsTask< Data >", "classucam_1_1fsttools_1_1SpeedStatsTask.html", null ],
      [ "ucam::fsttools::TuneWpWriteFstTask< Data, Arc >", "classucam_1_1fsttools_1_1TuneWpWriteFstTask.html", null ],
      [ "ucam::fsttools::WriteFstTask< Data, Arc >", "classucam_1_1fsttools_1_1WriteFstTask.html", null ],
      [ "ucam::hifst::CYKParserTask< Data >", "classucam_1_1hifst_1_1CYKParserTask.html", null ],
      [ "ucam::hifst::DumpNbestFeaturesTask< Data, Arc >", "classucam_1_1hifst_1_1DumpNbestFeaturesTask.html", null ],
      [ "ucam::hifst::GrammarTask< Data >", "classucam_1_1hifst_1_1GrammarTask.html", null ],
      [ "ucam::hifst::HifstStatsTask< Data >", "classucam_1_1hifst_1_1HifstStatsTask.html", null ],
      [ "ucam::hifst::HiFSTTask< Data, Arc, OptimizeT, CYKdataT, MultiUnionT, ExpandedNumStatesRTNT, ReplaceFstByArcT, RTNT >", "classucam_1_1hifst_1_1HiFSTTask.html", null ],
      [ "ucam::hifst::MultiThreadedCreateSentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1MultiThreadedCreateSentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::PatternsToInstancesTask< Data >", "classucam_1_1hifst_1_1PatternsToInstancesTask.html", null ],
      [ "ucam::hifst::PostProTask< Data, Arc >", "classucam_1_1hifst_1_1PostProTask.html", null ],
      [ "ucam::hifst::PreProTask< Data >", "classucam_1_1hifst_1_1PreProTask.html", null ],
      [ "ucam::hifst::ReferenceFilterTask< Data, Arc >", "classucam_1_1hifst_1_1ReferenceFilterTask.html", null ],
      [ "ucam::hifst::SentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1SentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::SingleThreadedCreateSentenceSpecificGrammarTask< Data >", "classucam_1_1hifst_1_1SingleThreadedCreateSentenceSpecificGrammarTask.html", null ],
      [ "ucam::hifst::SingleThreadedHifstClientTask< Data >", "classucam_1_1hifst_1_1SingleThreadedHifstClientTask.html", null ],
      [ "ucam::hifst::SparseWeightVectorLatticesTask< Data, Arc >", "classucam_1_1hifst_1_1SparseWeightVectorLatticesTask.html", null ],
      [ "ucam::lmbr::LmbrTask< Data >", "classucam_1_1lmbr_1_1LmbrTask.html", null ],
      [ "ucam::lmbr::MultiThreadedLmbrTask< Data >", "classucam_1_1lmbr_1_1MultiThreadedLmbrTask.html", null ],
      [ "ucam::lmbr::SingleThreadedLmbrTask< Data >", "classucam_1_1lmbr_1_1SingleThreadedLmbrTask.html", null ]
    ] ],
    [ "ucam::util::TaskInterface< DataT >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::hifst::LoadSparseWeightFlowerLatticeTask< DataT >", "classucam_1_1hifst_1_1LoadSparseWeightFlowerLatticeTask.html", [
        [ "ucam::hifst::LoadSparseWeightsTask< DataT >", "classucam_1_1hifst_1_1LoadSparseWeightsTask.html", null ]
      ] ]
    ] ],
    [ "ucam::util::TaskInterface< DataT< ArcT > >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::fsttools::MultiThreadedApplyLanguageModelTask< DataT, ArcT >", "classucam_1_1fsttools_1_1MultiThreadedApplyLanguageModelTask.html", null ],
      [ "ucam::fsttools::SingleThreadedApplyLanguageModelTask< DataT, ArcT >", "classucam_1_1fsttools_1_1SingleThreadedApplyLanguageModelTask.html", null ],
      [ "ucam::hifst::HifstServerTask< DataT, ArcT >", "classucam_1_1hifst_1_1HifstServerTask.html", null ],
      [ "ucam::hifst::MultiThreadedHifstTask< DataT, ArcT >", "classucam_1_1hifst_1_1MultiThreadedHifstTask.html", null ],
      [ "ucam::hifst::SingleThreadedHifstTask< DataT, ArcT >", "classucam_1_1hifst_1_1SingleThreadedHifstTask.html", null ]
    ] ],
    [ "ucam::util::TaskInterface< DataT< TupleArc32 > >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::hifst::MultiThreadedAliLatsToSparseVecLatsTask< DataT, ArcT >", "classucam_1_1hifst_1_1MultiThreadedAliLatsToSparseVecLatsTask.html", null ],
      [ "ucam::hifst::SingleThreadedAliLatsToSparseVecLatsTask< DataT, ArcT >", "classucam_1_1hifst_1_1SingleThreadedAliLatsToSparseVecLatsTask.html", null ]
    ] ],
    [ "ucam::util::TaskInterface< RuleIdsToSparseWeightLatsData<> >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::hifst::SingleThreadededRulesToWeightsSparseLatsTask", "classucam_1_1hifst_1_1SingleThreadededRulesToWeightsSparseLatsTask.html", null ]
    ] ],
    [ "ucam::util::TaskInterface< uh::HifstTaskData<> >", "classucam_1_1util_1_1TaskInterface.html", [
      [ "ucam::hifst::CYKParserTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1CYKParserTask.html", null ],
      [ "ucam::hifst::GrammarTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1GrammarTask.html", null ],
      [ "ucam::hifst::SentenceSpecificGrammarTask< uh::HifstTaskData<> >", "classucam_1_1hifst_1_1SentenceSpecificGrammarTask.html", null ]
    ] ],
    [ "Test", null, [
      [ "HifstTest", "classHifstTest.html", null ]
    ] ],
    [ "uk.ac.cam.eng.util.TestCommandLineInterface", "classuk_1_1ac_1_1cam_1_1eng_1_1util_1_1TestCommandLineInterface.html", null ],
    [ "uk.ac.cam.eng.rule.features.TestFeatureRegistry", "classuk_1_1ac_1_1cam_1_1eng_1_1rule_1_1features_1_1TestFeatureRegistry.html", null ],
    [ "TGMertAlgorithm< Arc, T >", "classTGMertAlgorithm.html", null ],
    [ "ucam::lmbr::Theta", "classucam_1_1lmbr_1_1Theta.html", null ],
    [ "ucam::fsttools::TopoFeaturesHelper< ActionT >", "structucam_1_1fsttools_1_1TopoFeaturesHelper.html", null ],
    [ "ucam::util::TrivialThreadPool", "classucam_1_1util_1_1TrivialThreadPool.html", null ],
    [ "uk.ac.cam.eng.extraction.hadoop.features.lexical.TTableClient", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1lexical_1_1TTableClient.html", null ],
    [ "TuneSet", "classTuneSet.html", null ],
    [ "ucam::fsttools::TuneSet< Arc >", "classucam_1_1fsttools_1_1TuneSet.html", null ],
    [ "TuneWpMain< Arc >", "classTuneWpMain.html", null ],
    [ "unary_function", null, [
      [ "hashfvecint64", "classhashfvecint64.html", null ],
      [ "ucam::util::HashFVec< VecT >", "classucam_1_1util_1_1HashFVec.html", null ]
    ] ],
    [ "uk.ac.cam.eng.extraction.hadoop.util.Util", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1Util.html", null ],
    [ "VectorToFunctionMapper< FromArc, T >", "classVectorToFunctionMapper.html", null ],
    [ "fst::VectorToStd< T >", "structfst_1_1VectorToStd.html", null ],
    [ "ucam::util::WordMapper", "classucam_1_1util_1_1WordMapper.html", null ],
    [ "fst::WordPenaltyMapper< Arc >", "classfst_1_1WordPenaltyMapper.html", null ],
    [ "ArrayList", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.TargetFeatureList", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1TargetFeatureList.html", null ]
    ] ],
    [ "ArrayWritable", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.TextArrayWritable", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1TextArrayWritable.html", null ]
    ] ],
    [ "Closeable", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.features.lexical.TTableServer", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1lexical_1_1TTableServer.html", null ]
    ] ],
    [ "Configured", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.extraction.ExtractorJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1extraction_1_1ExtractorJob.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.features.phrase.PhraseJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1phrase_1_1PhraseJob.html", [
        [ "uk.ac.cam.eng.extraction.hadoop.features.phrase.Source2TargetJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1phrase_1_1Source2TargetJob.html", null ],
        [ "uk.ac.cam.eng.extraction.hadoop.features.phrase.Target2SourceJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1phrase_1_1Target2SourceJob.html", null ]
      ] ],
      [ "uk.ac.cam.eng.extraction.hadoop.merge.MergeJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1merge_1_1MergeJob.html", null ]
    ] ],
    [ "EnumMap", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.FeatureMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1FeatureMap.html", null ]
    ] ],
    [ "FileOutputFormat", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.util.SimpleHFileOutputFormat", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1util_1_1SimpleHFileOutputFormat.html", null ]
    ] ],
    [ "HashMap", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.AlignmentCountMapWritable", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1AlignmentCountMapWritable.html", null ]
    ] ],
    [ "Map", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.ProvenanceCountMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1ProvenanceCountMap.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.ProvenanceProbMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1ProvenanceProbMap.html", null ]
    ] ],
    [ "Tool", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.extraction.ExtractorJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1extraction_1_1ExtractorJob.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.features.phrase.PhraseJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1features_1_1phrase_1_1PhraseJob.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.merge.MergeJob", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1merge_1_1MergeJob.html", null ]
    ] ],
    [ "Writable", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.AlignmentCountMapWritable", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1AlignmentCountMapWritable.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.ExtractedData", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1ExtractedData.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.FeatureMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1FeatureMap.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.ProvenanceCountMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1ProvenanceCountMap.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.ProvenanceProbMap", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1ProvenanceProbMap.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.RuleData", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1RuleData.html", null ],
      [ "uk.ac.cam.eng.extraction.hadoop.datatypes.TargetFeatureList", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1datatypes_1_1TargetFeatureList.html", null ]
    ] ],
    [ "WritableComparator", null, [
      [ "uk.ac.cam.eng.extraction.hadoop.merge.MergeComparator", "classuk_1_1ac_1_1cam_1_1eng_1_1extraction_1_1hadoop_1_1merge_1_1MergeComparator.html", null ]
    ] ]
];